letra = ARGV[0];

if letra == "n"
    letra.times do |i|
        letra.times do |j|
        print "*"
        end
        print "\n"
    end
    
    puts "*****"
    puts "*   *"
    puts "*   *"
    puts "*   *"
    puts "*****"
    
elsif letra == "0"
    puts "*****"
    puts "  *  "
    puts "  *   "
    puts "  *  "
    puts "*****"
elsif letra == "z"
    puts "*****"
    puts "   *"
    puts " *   "
    puts "*  "
    puts "*****"
elsif letra == "x"
    puts "*   *"
    puts " * * "
    puts "  *   "
    puts " * *"
    puts "*   *"
elsif letra == "z"
    puts "*   *"
    puts " * * "
    puts "  *   "
    puts " * *"
    puts "*   *"
elsif letra == "0"
    puts "*****"
    puts "**  *"
    puts "* * *"
    puts "*  **"
    puts "*****"
elsif letra == "0"
    puts "*   *"
    puts " * * "
    puts "  *   "
    puts " * *"
    puts "*   *"
elsif letra == "0"
    puts "   *"
    puts "  * * "
    puts " * * *"
    puts "* * * *"
    puts "   *   "
else
    
end